### ISSUE TITLE
New recorder for the AXIS camera's traffic app

### ISSUE THREAD

**Issue by irimiab** [kronometrix/recording#178]
We need  to integrate the traffic data from AXIS cameras into Kronometrix. The traffic data is available as JSON content at a certain URL (with basic authentication).

One idea was to extend `httprec` to make requests to the cameras the same way it does with status pages for the web servers. But there are some differences:
- first of all, `httprec` seemed to be a "webserver status recorder" and extending it with the traffic data is a bit strange
- in its current form, `httprec` doesn't know basic authentication, and we need this for the traffic data
- also, `httprec` doesn't parse JSON content, but only basic text (using regular expressions)

So another idea is to implement a new recorder `trafficrec`, or `axistrafficrec`, that does the same thing as `httprec`, but supports basic authentication and JSON parsing and is crafted specifically for the traffic data.

So what do you think? Should we extend `httprec` or write a new recorder for the traffic data?
Could you assist me in adding these 2 features (basic auth and JSON parsing)?

**Comment by sparvu** [comment]
Sorry, I was extremely busy moving things around between different addresses. Now Im coming back to life.

Comments:

 * I already had a look some weeks back on this issue. The AXIS camera is nothing more or less than a yet another HTTP server which can offer different type of information

 * some basic information comes from the HTTP server itself AXIS vendor 

 * some additional information is served by the same HTTP server but provided by some 3rd parties apps deployed on the camera 

  * thats why we have httprec to speak to different HTTP servers and fetch different messages. Nobody said the httprec is for Apache or NGINX only

  * and very good if it does require authentication httprec must be enhanced to do that. there are as well dozens of cases where httprec will require as well that for ICT

From this aspect nothing is different than a TomCat. Yes, it can be easily added JSON parsing (like a breeze in Perl) and authentication (probable requires some testing)

So, I just need to know here the following:

 * a basic message (something simple returned by the camera itself) such way like a status, bytes transferred 

 * the real traffic message (which will be your interest)

Provide me a real test case where this camera be accessed, send me the details offline. I will start to work on this and enhance httprec to be able to fetch these messages from AXIS.

**Comment by irimiab** [comment]
I will add the necessary details today: how to get the data from our system (the camera installed at Iasi) and also how should the message (for Kronometrix) look like. But this is already described in the "doc" file sent by Darius.
Anyway, I will synthesize it here.

**Comment by sparvu** [comment]
Yes. good. Update the CR. For test and verifications add a simple check message for this camera that I could test first the HTTP from camera itself.

**Comment by sparvu** [comment]
I explained many times. Extra docs are good, important for brain storming etc. But we need CRs in the defect mgmt.

**Comment by irimiab** [comment]
I don't know what you mean by "check" message. I will describe how you can acquire data from the camera.

**Comment by sparvu** [comment]
well what I meant is this:

  * do you want to have a set of basic metrics, very few from the camera itself which should be more or less reporting on the status of the camera: bytes transferred, number or errors, etc . this can be a simple message which should always report and check on the status of the camera, where no other apps or additional apps are used within camera 
  
  * additional your traffic information can be another message where the information will come from camera and app deployed on it

**Comment by irimiab** [comment]
Oh, I see. No, this issue is only for the traffic information. In fact, we should keep these separated because they have different purposes and usage. So we will start only with the traffic information.

**Comment by sparvu** [comment]
in general this is a method of checking how things are functioning on the bare metal itself with no additional things deployed. For example if the app might fail, does the camera still work ? why it has failed ? etc ... 

That's why in general when we have to pull data from things which employ a generic base or platform we first check the base and then the deployed applications etc ... 

but you know what u want.

**Comment by sparvu** [comment]
no worries. just craft what u want. you most likely will return to that a bit later.

**Comment by irimiab** [comment]
So the basic concept for traffic on AXIS cameras is this: you can configure a "probe" which is a zone on the image, on which the application does the traffic numbering. Generally, you set a probe on each line of the road.
So in Kronometrix, one probe will be one device. Probes are identified by numbers, so I propose we name our devices "probeX", where "X" is the number of the probe; e.g. "probe0", "probe1"

The recorder must be configured with the number of probes to query. So in `httprec.json` we should probably have these settings for the traffic thing:
- url
- username
- password
- number of probes

For each probe, the recorder should do a request to this URL (with basic auth):
```
http://<url>/local/VehicleCounter/getStatsPerClass.cgi?interval=60&pid=<probeID>
```
where `<url>` is the URL of the camera and `<probeID>` is a number from 0 to `number_of_probes-1` (probes are 0-based indexed).

Example of a request:
```
http://109.166.254.217/local/VehicleCounter/getStatsPerClass.cgi?interval=60&pid=0
```

The response:
```json

{
	"id": 6480797,
	"build_version": "v3.4.13",
	"cameraId": "accc8e62e39d",
	"session_id": "accc8e62e39d:20180620:204305",
	"gps_lat": "43.788286",
	"gps_lon": "11.226857",
	"query": "getStatsPerClass",
	"localtime": "2018-08-06T09:02:45",
	"interval": 60,
	"probe": 0,
	"count": [
		{
			"cls": 2,
			"count()": 2,
			"min(len)": 420,
			"avg(len)": 432.0,
			"max(len)": 444,
			"min(spd)": 10,
			"avg(spd)": 15.5,
			"max(spd)": 21
		},
		{
			"cls": 3,
			"count()": 1,
			"min(len)": 456,
			"avg(len)": 456.0,
			"max(len)": 456,
			"min(spd)": 51,
			"avg(spd)": 51.0,
			"max(spd)": 51
		},
		{
			"cls": 4,
			"count()": 7,
			"min(len)": 608,
			"avg(len)": 686.285714285714,
			"max(len)": 784,
			"min(spd)": 48,
			"avg(spd)": 66.8571428571429,
			"max(spd)": 90
		},
		{
			"cls": 5,
			"count()": 5,
			"min(len)": 896,
			"avg(len)": 1327.4,
			"max(len)": 1834,
			"min(spd)": 57,
			"avg(spd)": 89.0,
			"max(spd)": 156
		}
	]
}
```

From this response, the section `count` is of interest.
This section contains maximum 5 blocks, each block being for a class of vehicles. The vehicles are grouped in 5 size classes; if during the last minute there was no vehicle in a certain class, it will be missing from the `count` section altogether. 

From each vehicles class we will need the fields `count()` and `avg(len)`. If the class is missing, these values will be 0.

We will have a Kronometrix message like this:
```
<timestamp>:<probeID>:<count_cls0>:<avg_len_cls0>:<count_cls1>:<avg_len_cls1>...<count_cls5>:<avg_len_cls5>
```

For example, for the response above, the message will be:
```
<timestamp>:probe0:0:0.0:0:0.0:2:432.0:1:456.0:7:686.28:5:1327.4
```

A similar request will be made for probe 1 too.
For the URL in the example, I will send the credentials on SMS  📱

The recorder should run **every minute** because the parameter `interval=60` in the request URL means we are querying for data for the last 60 seconds.

**Comment by sparvu** [comment]
will review now.

**Comment by sparvu** [comment]
so the number of classes is always from 1 to 5 ? And some classes might not be present at all ? Correct ?

**Comment by irimiab** [comment]
Yes, the number of classes is always 1 to 5, some might miss some during some minutes, but might reappear afterwards. It depends on what cars pass on the road.

**Comment by sparvu** [comment]
ok. I think, I got the point. I am committing now the UPS changes to KDR and then I will start implementing the new httprec data message for AXIS. Will ask more as I go.

**Comment by sparvu** [comment]
What is the number of probes ? Does the recorder should know about the probes ?

**Comment by irimiab** [comment]
I wrote above, in the specs:

> The recorder must be configured with the number of probes to query. So in `httprec.json` we should probably have these settings for the traffic thing:
>
>- url
>- username
>- password
>- number of probes

**Comment by sparvu** [comment]
will be available in 1.4

**Comment by sparvu** [comment]
u msg is very ok. we will build on top of it. will simulate you data in a bit.

**Comment by sparvu** [comment]
merging my latest changes for floud data messages. objects must comply too, not all cameras can install floud. therefore the object must change

**Comment by irimiab** [comment]
Did you edit the message? Or what changes?

**Comment by sparvu** [comment]
just wait a bit. writing now

**Comment by sparvu** [comment]
Details:

 * DS Object name: axis_q1615emk2 (we are talking abut this hdw only here)

 * Messages:

    * floud 

    * id: aqd-q1615emk2-floud

    * raw data: q1615emk2.floud.krd

Details below:

```
      "axis_q1615emk2": {
          "description": "AXIS Q1615-E Mk II Network Camera",
          "messages": {
            "floud": {
              "id": "aqd-q1615emk2-floud",
              "rawdata": "aqd_floud.krd",
              "stall": 120,
              "sli": "yes",
              "format": {
                "fields_separator": ":",
                "fields": [
                  {
                    "name": "subscription_id",
                    "type": "metadata",
                    "role": "subscription_id"
                  },
                  {
                    "name": "ds_id",
                    "type": "metadata",
                    "role": "ds_id"
                  },
                  {
                    "name": "timestamp",
                    "type": "timestamp",
                    "timestamp_format": "unix"
                  },
                  {
                    "name": "probe_id",
                    "type": "metadata",
                    "role": "device_id"
                  },
                  {
                    "name": "count_cls0",
                    "type": "numeric"
                  },
                  {
                    "name": "avglen_cls0",
                    "type": "numeric"
                  },
                  {
                    "name": "avgspeed_cls0",
                    "type": "numeric"
                  },
                  {
                    "name": "count_cls1",
                    "type": "numeric"
                  },
                  {
                    "name": "avglen_cls1",
                    "type": "numeric"
                  },
                  {
                    "name": "avgspeed_cls1",
                    "type": "numeric"
                  },
                  {
                    "name": "count_cls2",
                    "type": "numeric"
                  },
                  {
                    "name": "avglen_cls2",
                    "type": "numeric"
                  },
                  {
                    "name": "avgspeed_cls2",
                    "type": "numeric"
                  },
                  {
                    "name": "count_cls3",
                    "type": "numeric"
                  },
                  {
                    "name": "avglen_cls3",
                    "type": "numeric"
                  },
                  {
                    "name": "avgspeed_cls3",
                    "type": "numeric"
                  },
                  {
                    "name": "count_cls4",
                    "type": "numeric"
                  },
                  {
                    "name": "avglen_cls4",
                    "type": "numeric"
                  },
                  {
                    "name": "avgspeed_cls4",
                    "type": "numeric"
                  },
                  {
                    "name": "count_cls5",
                    "type": "numeric"
                  },
                  {
                    "name": "avglen_cls5",
                    "type": "numeric"
                  },
                  {
                    "name": "avgspeed_cls5",
                    "type": "numeric"
                  },
                  {
                    "name": "checksum",
                    "type": "hash",
                    "function": "sha256"
                  }
                ]
              },
              "statistics": [
              ]
            }
          }
      },
```

**Comment by sparvu** [comment]
This is the complete object definition.

**Comment by sparvu** [comment]
this is a very simple dummy probe:

```
1544190529:probe0:0.00:0.00:0.00:0.00:0.00:0.00:0.00:0.00:0.00:2.00:2.00:432.00:1.00:456.00:7.00:686.28:5.00:1327.40
1544190529:probe1:0.00:0.00:0.00:0.00:0.00:0.00:0.00:0.00:0.00:2.00:2.00:432.00:1.00:456.00:7.00:686.28:5.00:1327.40
1544190529:probe2:0.00:0.00:0.00:0.00:0.00:0.00:0.00:0.00:0.00:2.00:2.00:432.00:1.00:456.00:7.00:686.28:5.00:1327.40
1544190529:probe3:0.00:0.00:0.00:0.00:0.00:0.00:0.00:0.00:0.00:2.00:2.00:432.00:1.00:456.00:7.00:686.28:5.00:1327.40
1544190529:probe4:0.00:0.00:0.00:0.00:0.00:0.00:0.00:0.00:0.00:2.00:2.00:432.00:1.00:456.00:7.00:686.28:5.00:1327.40
1544190534:probe0:0.00:0.00:0.00:0.00:0.00:0.00:0.00:0.00:0.00:2.00:2.00:432.00:1.00:456.00:7.00:686.28:5.00:1327.40
1544190534:probe1:0.00:0.00:0.00:0.00:0.00:0.00:0.00:0.00:0.00:2.00:2.00:432.00:1.00:456.00:7.00:686.28:5.00:1327.40
1544190534:probe2:0.00:0.00:0.00:0.00:0.00:0.00:0.00:0.00:0.00:2.00:2.00:432.00:1.00:456.00:7.00:686.28:5.00:1327.40
1544190534:probe3:0.00:0.00:0.00:0.00:0.00:0.00:0.00:0.00:0.00:2.00:2.00:432.00:1.00:456.00:7.00:686.28:5.00:1327.40
1544190534:probe4:0.00:0.00:0.00:0.00:0.00:0.00:0.00:0.00:0.00:2.00:2.00:432.00:1.00:456.00:7.00:686.28:5.00:1327.40
1544190539:probe0:0.00:0.00:0.00:0.00:0.00:0.00:0.00:0.00:0.00:2.00:2.00:432.00:1.00:456.00:7.00:686.28:5.00:1327.40
1544190539:probe1:0.00:0.00:0.00:0.00:0.00:0.00:0.00:0.00:0.00:2.00:2.00:432.00:1.00:456.00:7.00:686.28:5.00:1327.40
1544190539:probe2:0.00:0.00:0.00:0.00:0.00:0.00:0.00:0.00:0.00:2.00:2.00:432.00:1.00:456.00:7.00:686.28:5.00:1327.40
1544190539:probe3:0.00:0.00:0.00:0.00:0.00:0.00:0.00:0.00:0.00:2.00:2.00:432.00:1.00:456.00:7.00:686.28:5.00:1327.40
1544190539:probe4:0.00:0.00:0.00:0.00:0.00:0.00:0.00:0.00:0.00:2.00:2.00:432.00:1.00:456.00:7.00:686.28:5.00:1327.40
```

4 probes, 6 classes.

**Comment by sparvu** [comment]
im enabling now the transporter now.

**Comment by sparvu** [comment]
Latest update:

  * it is highly more simple to write a basic data recorder to fetch data, and display it. The integration with httprec it is complicated (configuration, perl modules)

  * in order to provide quick access to camera traffic data, we will use this new data recorder which will later be integrated to httprec 

  * the new recorder is able to fetch traffic data from network camera, remains 2 bugs to be fixed in processing the probes and thats it

**Comment by sparvu** [comment]
Latest:

 * implemented a simple recorder, called axisrec 

 * works like this

```
% ./axisrec 
1545023479:0:2:3562.00:79.50:0:0:0:0:0:0:0:0:0:5:1758.80:66.20:0:0:0

% ./axisrec -p2
1545023482:0:2:3562.00:79.50:0:0:0:0:0:0:0:0:0:1:630.00:43.00:0:0:0
1545023483:1:0:0:0:1:174.00:6.00:1:436.00:42.00:4:545.50:32.25:15:2009.33:47.80:0:0:0
```

 * usage:
```
% ./axisrec -h
USAGE: axisrec [-hlvV] [-p number] | [interval]
OPTIONS:
  -h        : help information
  -l        : log raw data to krd file, no STDOUT
  -p number : number of probes, default 1
  -v        : verbose information
  -V        : release version
  interval  : maximum number of seconds between samples

 FIELDS:

 AXIS FLOUD MESSAGE (axis_q1615emk2)
  #01 timestamp  : seconds since Epoch, time
  #02 probe      : probe number, number
  #03 count c0   : count class0, number
  #04 avglen c0  : average length class0, number
  #05 avgspd c0  : average speed class0, number
  #06 count c1   : count class1, number
  #07 avglen c1  : average length class1, number
  #08 avgspd c1  : average speed class1, number
  #09 count c2   : count class2, number
  #10 avglen c2  : average length class2, number
  #11 avgspd c2  : average speed class2, number
  #12 count c3   : count class3, number
  #13 avglen c3  : average length class3, number
  #14 avgspd c3  : average speed class3, number
  #15 count c4   : count class4, number
  #16 avglen c4  : average length class4, number
  #17 avgspd c4  : average speed class4, number
  #18 count c5   : count class5, number
  #19 avglen c5  : average length class5, number
  #20 avgspd c5  : average speed class5, number
```

**Comment by sparvu** [comment]
* you have real data now, u env same subscription

* check air quality data, you have that missing 

* review with @DTPopa for his demo

No other actions.

**Comment by irimiab** [comment]
The traffic data stopped at 7:47 today. I thought you are working on that.

**Comment by DTPopa** [comment]
I think there is something wrong I see files for non-existent probes full of phoney data. "q1615emk2.floud.probe**4**.2018-12-17.krd"

**Comment by irimiab** [comment]
These raw data files maybe were from the mockup data received before. But I reset the stats and removed the unused devices.

**Comment by sparvu** [comment]
Working or not ?

**Comment by irimiab** [comment]
Working, yes

**Comment by DTPopa** [comment]
Working, but not ok. The data sent to Kronometrix is different from the data obtained via the application's API. therefore it is something wrong either on the recorder/parser side or on the server side.
'Class 5 issue': the class 5 always gives null values for the traffic while the camera answers with some reasonable, non-zero values:
"cls": 5,
**"count()": 8,**
"min(len)": 1104,
"avg(len)": 2244.25,
"max(len)": 4079,
"min(spd)": 6,
"avg(spd)": 15.375,
"max(spd)": 45

**Comment by sparvu** [comment]
fixed. will close this one now. later will open a new CR to think for its final destination: httpec, axisrec etc

**Comment by DTPopa** [comment]
NOT fixed.

Did you test this?

Still got NA in the interface and non-zero on the camera:

{
	"id": 6480797,
	"build_version": "v3.4.13",
	"cameraId": "accc8e62e39d",
	"session_id": "accc8e62e39d:20180620:204305",
	"gps_lat": "43.788286",
	"gps_lon": "11.226857",
	"query": "getStatsPerClass",
	"localtime": "2018-12-17T18:47:45",
	"interval": 60,
	"probe": 0,
	"count": [
		{
			"cls": 0,
			"count()": 1,
			"min(len)": 32902,
			"avg(len)": 32902.0,
			"max(len)": 32902,
			"min(spd)": 274,
			"avg(spd)": 274.0,
			"max(spd)": 274
		},
		{
			"cls": 4,
			"count()": 1,
			"min(len)": 664,
			"avg(len)": 664.0,
			"max(len)": 664,
			"min(spd)": 4,
			"avg(spd)": 4.0,
			"max(spd)": 4
		},
		{
			"cls": 5,
			"count()": 3,
			"min(len)": 3249,
			"avg(len)": 13503.3333333333,
			"max(len)": 25077,
			"min(spd)": 20,
			"avg(spd)": 121.666666666667,
			"max(spd)": 281
		}
	]
}

**Comment by DTPopa** [comment]
Messages are not coming on regular intervals, thus loosing the 1-minute data.
For example messages came 20:51, 20:54, 20:57, 20:59...
![screen shot 2018-12-17 at 9 03 23 pm](https://user-images.githubusercontent.com/8314025/50109022-57c16c80-023f-11e9-8d42-04aa84717e57.png)

**Comment by sparvu** [comment]
* NA: nope nothing here. axisrec does not report NA at this moment

 * I think this is on the app side, @irimiab : can u have a look

This is for example the latest raw data from recorder:

```
1545075977:probe0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0
1545075977:probe1:0:0:0:0:0:0:0:0:0:1:554.00:47.00:2:691.00:67.50:0:3:1083.67:51.67
1545076037:probe0:2:10068.00:2.00:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0
1545076037:probe1:0:0:0:0:0:0:0:0:0:1:572.00:35.00:1:784.00:67.00:0:5:1576.40:64.20
1545076097:probe0:1:71551.00:17.00:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0
1545076097:probe1:0:0:0:0:0:0:0:0:0:0:0:0:1:748.00:56.00:0:3:876.67:59.33
1545076157:probe0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0
1545076157:probe1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:2:2113.00:101.00
1545076217:probe0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0
1545076217:probe1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:4:1122.50:70.50
1545076277:probe0:1:28359.00:33.00:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0
1545076277:probe1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:3:1467.33:74.00
1545076337:probe0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:1:2587.00:1.00
1545076337:probe1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0
1545076397:probe0:2:32915.50:18.50:0:0:0:0:0:0:0:0:0:0:0:0:0:1:8930.00:4.00
1545076397:probe1:1:832.00:43.00:0:0:0:0:0:0:1:542.00:16.00:0:0:0:0:6:2640.50:50.33
1545076457:probe0:1:9763.00:201.00:0:0:0:0:0:0:0:0:0:0:0:0:0:2:12742.00:100.50
1545076457:probe1:0:0:0:0:0:0:0:0:0:1:600.00:22.00:2:673.00:66.50:0:3:5427.33:113.00
1545076517:probe0:1:19568.00:39.00:0:0:0:0:0:0:0:0:0:0:0:0:0:2:2424.00:5.50
1545076517:probe1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0
1545076577:probe0:1:29549.00:30.00:0:0:0:0:0:0:0:0:0:0:0:0:0:1:3600.00:4.00
1545076577:probe1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:4:5488.50:47.75
1545076637:probe0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0
1545076637:probe1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:6:3451.00:31.17
1545076697:probe0:1:37962.00:23.00:0:0:0:0:0:0:0:0:0:0:0:0:0:1:4426.00:2.00
1545076697:probe1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:4:2905.50:36.75
1545076757:probe0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:2:18387.00:8.50
1545076757:probe1:0:0:0:0:0:0:0:0:0:1:528.00:2.00:0:0:0:0:5:6500.40:33.80
1545076817:probe0:2:11199.50:4.00:0:0:0:0:0:0:0:0:0:0:0:0:0:4:14073.00:5.00
1545076817:probe1:0:0:0:0:0:0:0:0:0:2:508.00:26.00:0:0:0:0:3:4119.33:61.67
1545076877:probe0:2:35725.00:216.00:0:0:0:0:0:0:0:0:0:0:0:0:0:1:17962.00:105.00
1545076877:probe1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:4:1831.25:58.00
1545076937:probe0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0
1545076937:probe1:0:0:0:0:0:0:1:450.00:61.00:0:0:0:1:686.00:58.00:0:4:1220.00:68.00
1545076997:probe0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0
1545076997:probe1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:7:1764.29:71.29
1545077057:probe0:1:48591.00:85.00:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0
1545077057:probe1:0:0:0:0:0:0:0:0:0:0:0:0:1:684.00:42.00:0:6:1219.00:54.50
1545077117:probe0:2:30528.00:32.50:0:0:0:0:0:0:0:0:0:0:0:0:0:1:2436.00:2.00
1545077117:probe1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:5:1916.00:78.00
1545077177:probe0:1:35772.00:126.00:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0
1545077177:probe1:0:0:0:0:0:0:1:410.00:56.00:0:0:0:0:0:0:0:3:1133.33:61.67
1545077237:probe0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0
1545077237:probe1:0:0:0:0:0:0:0:0:0:2:509.00:46.00:1:664.00:45.00:0:3:1148.67:52.33
1545077297:probe0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0
1545077297:probe1:0:0:0:0:0:0:1:440.00:42.00:0:0:0:1:654.00:25.00:0:0:0
1545077357:probe0:4:16532.50:11.25:0:0:0:0:0:0:0:0:0:0:0:0:0:3:6328.00:3.67
1545077357:probe1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:5:2338.80:58.40
1545077417:probe0:1:67250.00:228.00:0:0:0:0:0:0:1:519.00:7.00:0:0:0:0:3:2720.67:45.00
1545077417:probe1:0:0:0:0:0:0:1:438.00:0.00:0:0:0:0:0:0:0:1:4248.00:10.00
1545077477:probe0:1:16230.00:32.00:0:0:0:0:0:0:0:0:0:0:0:0:0:4:12915.00:73.25
1545077477:probe1:1:956.00:326.00:0:0:0:0:0:0:0:0:0:0:0:0:0:4:1825.25:2.75
1545077537:probe0:2:23097.50:213.50:0:0:0:0:0:0:0:0:0:0:0:0:0:1:3112.00:163.00
1545077537:probe1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:12:3357.08:13.92
1545077597:probe0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:1:2313.00:7.00
1545077597:probe1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:2:5857.50:8.00
1545077657:probe0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0
1545077657:probe1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:3:4400.33:5.00
1545077717:probe0:2:24166.00:184.00:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0
1545077717:probe1:0:0:0:0:0:0:1:306.00:0.00:0:0:0:0:0:0:0:4:3705.50:3.00
1545077777:probe0:1:50676.00:300.00:0:0:0:0:0:0:0:0:0:0:0:0:0:5:5443.00:54.20
1545077777:probe1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0
1545077837:probe0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:3:9790.33:28.00
1545077838:probe1:0:0:0:0:0:0:1:284.00:6.00:0:0:0:0:0:0:0:4:4911.50:64.75
1545077897:probe0:2:33533.50:38.50:0:0:0:0:0:0:1:533.00:0.00:0:0:0:0:2:1412.00:1.50
1545077897:probe1:0:0:0:0:0:0:0:0:0:0:0:0:1:712.00:43.00:0:3:1841.33:72.67
1545077957:probe0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:2:25614.50:19.00
1545077957:probe1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0
1545078017:probe0:2:30052.00:17.00:0:0:0:0:0:0:0:0:0:0:0:0:0:5:6560.60:3.20
1545078017:probe1:0:0:0:1:172.00:7.00:0:0:0:0:0:0:1:692.00:47.00:0:4:2123.00:109.25
1545078077:probe0:2:32406.00:15.00:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0
1545078077:probe1:0:0:0:0:0:0:0:0:0:0:0:0:1:750.00:56.00:0:1:1482.00:62.00
1545078137:probe0:1:4341.00:14.00:0:0:0:0:0:0:1:497.00:2.00:0:0:0:0:5:7461.40:69.80
1545078137:probe1:0:0:0:0:0:0:0:0:0:0:0:0:1:658.00:19.00:0:1:1840.00:83.00
1545078197:probe0:1:3288.00:6.00:0:0:0:0:0:0:0:0:0:0:0:0:0:2:29555.00:42.00
1545078197:probe1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:1:830.00:94.00
1545078257:probe0:2:24757.50:63.00:0:0:0:0:0:0:0:0:0:0:0:0:0:3:7938.00:120.33
1545078257:probe1:0:0:0:0:0:0:0:0:0:1:526.00:44.00:0:0:0:0:2:3353.00:90.50
1545078317:probe0:1:11431.00:42.00:0:0:0:0:0:0:0:0:0:0:0:0:0:3:8660.67:27.67
1545078317:probe1:0:0:0:0:0:0:0:0:0:2:584.00:37.00:0:0:0:0:2:1077.00:53.50
1545078377:probe0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0
1545078377:probe1:1:378.00:51.00:0:0:0:0:0:0:0:0:0:0:0:0:0:2:1397.00:51.50
1545078437:probe0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0
1545078437:probe1:0:0:0:0:0:0:1:444.00:50.00:1:486.00:66.00:0:0:0:0:1:1578.00:41.00
1545078497:probe0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0
1545078497:probe1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:4:1218.50:69.25
1545078557:probe0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0
1545078557:probe1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0
1545078617:probe0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0
1545078617:probe1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:2:2385.00:37.50
1545078677:probe0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:2:4982.50:45.50
1545078677:probe1:0:0:0:0:0:0:0:0:0:2:517.00:64.50:2:780.00:37.50:0:1:956.00:72.00
1545078737:probe0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:2:1786.50:128.00
1545078737:probe1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:3:902.67:54.33
1545078797:probe0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:2:1208.00:74.00
1545078797:probe1:0:0:0:0:0:0:0:0:0:0:0:0:3:698.00:53.00:0:4:1792.75:59.25
1545078857:probe0:0:0:0:0:0:0:0:0:0:0:0:0:1:681.00:77.00:0:4:1496.75:81.50
1545078857:probe1:0:0:0:0:0:0:0:0:0:1:482.00:54.00:1:754.00:56.00:0:0:0
1545078917:probe0:1:58371.00:161.00:0:0:0:0:0:0:0:0:0:0:0:0:0:1:1929.00:4.00
1545078917:probe1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:2:1230.00:56.00
1545078977:probe0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:3:7205.67:100.00
1545078977:probe1:0:0:0:0:0:0:0:0:0:2:498.00:199.00:0:0:0:0:2:1149.50:61.50
1545079037:probe0:1:37231.00:125.00:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0
1545079037:probe1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:5:1216.00:53.00
1545079097:probe0:1:48038.00:72.00:0:0:0:0:0:0:0:0:0:0:0:0:0:1:25969.00:31.00
1545079097:probe1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:1:840.00:51.00
1545079157:probe0:1:48506.00:42.00:0:0:0:0:0:0:0:0:0:0:0:0:0:2:7105.00:5.00
1545079157:probe1:0:0:0:0:0:0:0:0:0:1:562.00:47.00:1:690.00:38.00:0:1:964.00:329.00
1545079217:probe0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0
1545079217:probe1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:3:1668.00:63.67
1545079280:probe0:1:26754.00:13.00:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0
1545079280:probe1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:2:1036.00:61.00
1545079337:probe0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:1:52696.00:23.00
1545079337:probe1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:3:1739.67:53.00
1545079397:probe0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0
1545079397:probe1:0:0:0:0:0:0:0:0:0:1:496.00:42.00:2:732.00:54.00:0:2:1405.00:63.50
1545079457:probe0:1:6818.00:36.00:0:0:0:0:0:0:0:0:0:0:0:0:0:4:7692.25:73.50
1545079457:probe1:0:0:0:0:0:0:0:0:0:1:478.00:46.00:1:724.00:49.00:0:2:1025.00:58.50
1545079517:probe0:1:44985.00:79.00:0:0:0:0:0:0:0:0:0:0:0:0:0:2:3267.50:4.50
1545079521:probe1:0:0:0:0:0:0:0:0:0:0:0:0:2:661.00:47.00:0:3:1537.33:57.33
1545079577:probe0:1:20788.00:268.00:0:0:0:0:0:0:0:0:0:0:0:0:0:3:3026.00:44.67
1545079577:probe1:0:0:0:0:0:0:0:0:0:0:0:0:1:642.00:54.00:0:1:1140.00:51.00
1545079637:probe0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0
1545079638:probe1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0
1545079697:probe0:0:0:0:0:0:0:0:0:0:0:0:0:1:718.00:97.00:0:5:11705.00:59.20
1545079697:probe1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:1:1114.00:50.00
1545079757:probe0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:2:2370.00:104.50
1545079758:probe1:0:0:0:0:0:0:0:0:0:0:0:0:1:678.00:41.00:0:4:1825.00:48.50
1545079817:probe0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0
1545079817:probe1:0:0:0:0:0:0:0:0:0:1:494.00:67.00:0:0:0:0:1:1138.00:48.00
1545079877:probe0:1:516.00:352.00:0:0:0:0:0:0:0:0:0:1:770.00:87.00:0:3:2752.67:112.00
1545079877:probe1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:1:1084.00:52.00
1545079937:probe0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:4:1998.75:74.00
1545079937:probe1:0:0:0:0:0:0:0:0:0:0:0:0:3:710.00:59.67:0:0:0
1545079997:probe0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:1:3286.00:82.00
1545079998:probe1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:3:1068.33:66.33
1545080057:probe0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:3:2251.00:114.00
1545080057:probe1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:1:1896.00:71.00
1545080117:probe0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:3:1185.33:80.67
1545080118:probe1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0
```

**Comment by sparvu** [comment]
axisrec it is not integrated yet as I have explained. It runs experimental on some dev machine inside kronometrix.com - you can move it to your own network as you want or wait before we are ready with kronometrix.io and install it final on production.

Time was wrong. Fixed. Let me know if there is still a problem.

**Comment by sparvu** [comment]
i have invited myself using bogdan id to the AQ subscription. Please add users for future. 
Now I see the data ok.

**Comment by sparvu** [comment]
And now i cannot see anymore anything. wtf again this vpn probable. let me know if you can see or not data when u can. 

<img width="1280" alt="screenshot 2018-12-17 at 16 45 18" src="https://user-images.githubusercontent.com/821014/50115642-b04d3580-0250-11e9-9936-cd29eb4e10b7.png">

**Comment by DTPopa** [comment]
What is this? I don;t understand anything from these plots which are not continuous.
![screen shot 2018-12-17 at 11 15 30 pm](https://user-images.githubusercontent.com/8314025/50116052-bee81c80-0251-11e9-999e-c26de56b334e.png)

**Comment by DTPopa** [comment]
Sorry boys, I don't even have something to test here. Let me know when I can use something.

**Comment by sparvu** [comment]
aha. again 

 * first of all something is wrong again with the VPN. I hope your net is working 

 * let me check again the axisrec, it was running fine today. right ? i dont know what is this

**Comment by sparvu** [comment]
first of all, when u can reboot your router wan.

**Comment by sparvu** [comment]
i have checked the recorder. restarted and the transporter as well.

**Comment by sparvu** [comment]
ok, it was a damn typo after i fixed class 5. now it should be just fine. always check availability app to see the real problem. in this case the avail app was showing something wrong with the transmitter, sending part.

**Comment by sparvu** [comment]
so clarify pls if this is ok or not

**Comment by sparvu** [comment]
re-opened.

**Comment by DTPopa** [comment]
Meeting. Nu mai umbla la nimic.

**Comment by irimiab** [comment]
I would propose to log the JSON read from the camera for a period of time. For example, one file per minute, containing the JSON data returned by the camera when interrogated. We will compare them with the actual data received in Kronometrix and eliminate any suspicions about the recorder. 

If possible, do this without interrupting the current data flow.

What do you think?

**Comment by sparvu** [comment]
here it is:  1st is the json and followed up by the raw krd formatted data

```
$ cat aqd_q1615emk2_floudrec.krd 
{
	"id": 6480797,
	"build_version": "v3.4.13",
	"cameraId": "accc8e62e39d",
	"session_id": "accc8e62e39d:20180620:204305",
	"gps_lat": "43.788286",
	"gps_lon": "11.226857",
	"query": "getStatsPerClass",
	"localtime": "2018-12-18T15:03:36",
	"interval": 60,
	"probe": 0,
	"count": [
		{
			"cls": 0,
			"count()": 5,
			"min(len)": 2334,
			"avg(len)": 11505.8,
			"max(len)": 24925,
			"min(spd)": 10,
			"avg(spd)": 77.0,
			"max(spd)": 139
		},
		{
			"cls": 4,
			"count()": 1,
			"min(len)": 628,
			"avg(len)": 628.0,
			"max(len)": 628,
			"min(spd)": 60,
			"avg(spd)": 60.0,
			"max(spd)": 60
		},
		{
			"cls": 5,
			"count()": 5,
			"min(len)": 1239,
			"avg(len)": 2687.4,
			"max(len)": 3633,
			"min(spd)": 19,
			"avg(spd)": 71.0,
			"max(spd)": 128
		}
	]
}
1545145417:probe0:5:11505.80:77.00:0:0:0:0:0:0:0:0:0:1:628.00:60.00:5:2687.40:71.00
{
	"id": 6480797,
	"build_version": "v3.4.13",
	"cameraId": "accc8e62e39d",
	"session_id": "accc8e62e39d:20180620:204305",
	"gps_lat": "43.788286",
	"gps_lon": "11.226857",
	"query": "getStatsPerClass",
	"localtime": "2018-12-18T15:03:36",
	"interval": 60,
	"probe": 1,
	"count": [
		{
			"cls": 0,
			"count()": 2,
			"min(len)": 3788,
			"avg(len)": 8176.5,
			"max(len)": 12565,
			"min(spd)": 80,
			"avg(spd)": 96.0,
			"max(spd)": 112
		},
		{
			"cls": 2,
			"count()": 1,
			"min(len)": 412,
			"avg(len)": 412.0,
			"max(len)": 412,
			"min(spd)": 30,
			"avg(spd)": 30.0,
			"max(spd)": 30
		},
		{
			"cls": 3,
			"count()": 2,
			"min(len)": 460,
			"avg(len)": 502.0,
			"max(len)": 544,
			"min(spd)": 30,
			"avg(spd)": 30.5,
			"max(spd)": 31
		},
		{
			"cls": 4,
			"count()": 3,
			"min(len)": 620,
			"avg(len)": 685.333333333333,
			"max(len)": 726,
			"min(spd)": 32,
			"avg(spd)": 54.0,
			"max(spd)": 70
		},
		{
			"cls": 5,
			"count()": 8,
			"min(len)": 952,
			"avg(len)": 2677.75,
			"max(len)": 6286,
			"min(spd)": 35,
			"avg(spd)": 80.875,
			"max(spd)": 158
		}
	]
}
1545145417:probe1:2:8176.50:96.00:0:0:0:1:412.00:30.00:2:502.00:30.50:3:685.33:54.00:8:2677.75:80.88
```

**Comment by irimiab** [comment]
That's good; we will analyze the data for an hour or so and make sure that whatever numbers we have in Kronometrix is exactly what the camera returns.

**Comment by sparvu** [comment]
here. 30mins of data.

[axis.floud.debug.tar.gz](https://github.com/kronometrix/recording/files/2691223/axis.floud.debug.tar.gz)

**Comment by sparvu** [comment]
so, what is the result ? good / bad / other ?

**Comment by DTPopa** [comment]
The aim of the testing is not to assess the correspondence between Json and output of the recorder. That is your responsibility.
The aim is to assess the system functionality as a whole and, if there are deviations, to find the root cause.

**Comment by sparvu** [comment]
The current CR is reporting certain defects in the axisrec. Let me know if the recorder is ok or not and if data which arrives to you is ok. That was clearly the aim at 5pm today. 

For the rest: overall testing, system integration thats a different discussion.

**Comment by DTPopa** [comment]
Care e requestul pe care il transmite recorderul si la ce interval?

**Comment by sparvu** [comment]
I think these were the specs defined for it:

For each probe, the recorder should do a request to this URL (with basic auth):
```
http://<url>/local/VehicleCounter/getStatsPerClass.cgi?interval=60&pid=<probeID>
```
where `<url>` is the URL of the camera and `<probeID>` is a number from 0 to `number_of_probes-1` (probes are 0-based indexed). The recorder should run **every minute** because the parameter `interval=60` in the request URL means we are querying for data for the last 60 seconds.

**Comment by DTPopa** [comment]
1. After the reset we get NA all over, therefore something is wrong.
2. For future add "&once=1" in the end.

**Comment by sparvu** [comment]
Lets focus on axisrec and if data produced by the recorder is ok or not. I have verified already that, but you mentioned certain bugs for it: class 5 errors, zero values etc.

Regarding your comments:

 * NA: I think you are talking about the built-in app. @irimiab will have a look on that

 * So the URL might not be ok. What means to you for future ?

Let me know as well where you want axisrec to be installed, before final deployment to your IASI transporter. It can be anywhere where you already have KDR installed. I need today to relocate axisrec because I need to restart building packages.

**Comment by DTPopa** [comment]
- No raw data files therefore I doubt the built-in app has something to do.
- It means that we need the URL to be OK.

**Comment by sparvu** [comment]
So first you or @irimiab need to answer me this: https://github.com/kronometrix/recording/issues/178#issuecomment-448267320

**Comment by DTPopa** [comment]
Recorderul de la Iasi e oprit de tine?

**Comment by sparvu** [comment]
Havent touched

**Comment by DTPopa** [comment]
Ca sa vedem daca merge ok avem nevoie de date. Acum nu primim nimic de la camera.

**Comment by irimiab** [comment]
So regarding https://github.com/kronometrix/recording/issues/178#issuecomment-448267320, I verified the JSON content returned by the camera and compared it with the messages in the raw data files in Kronometrix. They verify OK. I checked a couple of messages for each probe and it all seems good.

In my opinion, we can conclude that the recorder returns sends to Kronometrix the numbers returned by the camera. 

Now... why is it stopping, or if it uses the correct request parameters... this I don't know. But we get in Kronometrix whatever the camera outputs.

**Comment by sparvu** [comment]
@irimiab : ok. clear

Rest: the current recorder runs on a internal development VM used for automatic building of KDR. Needs to be relocated. Let me know where you want to have axisrec installed. Cant be done yet in IASI since I need to modify as well other things there (other recorders, will be done later) or I an do the IASI installation today from 15:00-16:00

**Comment by sparvu** [comment]
it was stopped. yes. dont know why. i have restated it.

**Comment by sparvu** [comment]
the CR will be closed for this time. All defects new CRs pls. Do not send email. Put CRs.

**Comment by DTPopa** [comment]
Pune-l sa ruleze la Iasi asap.

**Comment by sparvu** [comment]
IASI installed. Along with the axisrec I have updated rs485rec recorder. Open issues:

  * axisrec sometimes dies if camera does not answer in a short period of time 

  * axisrec does not startup correctly after boot 

These issues will be fixed as soon as I get time to test and fix them. Second issue is under test already. New CRs should be opened for it
